fix(deps): Update dependencies
relaycorp/relaynet-gateway-android pull request #623
Opened 2022-06-02 14:01 UTC by Filmaluco

2022-06-02 14:28 UTC, sdsantos approved these changes

2022-06-02 14:28 UTC, sdsantos commented on app/src/main/res/xml/data_extraction_rules.xml
> +        <include domain="sharedpref" path="pref_courier.xml"/>
Couldn't it be * here as well?

2022-06-06 09:29 UTC, gnarea requested changes

2022-06-06 09:29 UTC, gnarea commented on app/build.gradle
> +    implementation "tech.relaycorp:doh:1.0.4" // needs ktor update as well to avoid conflicts
This kind of comments are best kept in the PR (as inline comments) as they're only relevant in this PR. Also in this particular case it's on the GH issue with the big TODO list.

2022-06-06 09:29 UTC, gnarea commented on app/build.gradle
> +    implementation 'com.fredporciuncula:flow-preferences:1.5.0' // needs a higher version of kotlin
Ditto.

2022-06-06 09:29 UTC, gnarea commented on app/lint.xml
> +        <ignore path="**/kotlinx-coroutines-core-jvm-1.5.2.jar" />
Please include the reason for ignoring these packages (see Bouncy Castle entry above). This is partly to make sure we aren't silencing issues that we should actually be fixing, and partly to document the offending dependency (to remove the entry if the dependency is dropped in the future).

2022-06-06 09:29 UTC, gnarea commented on build.gradle
> +        maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
Why do we need snapshots in the production code?

2022-06-06 15:57 UTC, Filmaluco commented on app/build.gradle
> +    implementation 'com.fredporciuncula:flow-preferences:1.5.0'
// needs a higher version of kotlin

2022-06-06 15:58 UTC, Filmaluco commented on app/build.gradle
>      // Local and Internet-based Parcel Delivery Connections (PDCs)
`    implementation "tech.relaycorp:doh:1.0.4"` needs ktor update as well to avoid conflicts

2022-06-08 11:32 UTC, gnarea approved these changes
Obrigado!

2022-06-08 11:36 UTC, merged